name: streamer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  # Misc
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  cached_network_image: ^3.2.0
  better_player: ^0.0.81

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Routing
  auto_route: ^3.2.4

  # Logging
  logger: ^1.1.0

  # Caching
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
